import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh Bellingham Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main>
        <section className=" bg-zinc-900 h-screen"> 
        {/*When I left off, I was unable to figure out why Tailwind won't update the bg color on the local host*/}
          <h1>Hello</h1>
        </section>
      </main>

    </div>
  )
}
