import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai'
import Image from "next/image";
import deved from "../public/dev-ed.wave.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh Bellingham Portfolio</title>
        <meta name="description" content="Generated by cre" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <section className="min-h-screen"> 
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-lg font-poppins">Portfolio Site</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer, text-xl" />
              </li>
              <li>
                <a 
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8" 
                  href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Josh Bellingham</h2>
            <h3 className="text-md py-5 leading-8 text-gray-900">UX Designer</h3>
            <p>This is a paragraph that is my description as a person</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
          </div>
          <div>{/* This div is for an image in the future*/}</div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I design stuff.
              This is how to do a <span className=" text-teal-500">link</span>
              </p>
          </div>
          <div>
            <div>
             {/*This div is for "cards?"*/}
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
